/casher 指名欄を作る
toririm/cafeore-2024 pull request #187
Opened 2024-10-03 05:40 UTC by Astalum

fix #177

2024-10-03 06:02 UTC, Astalum commented
@toririm

2024-10-03 06:04 UTC, toririm commented
@Astalum 
`bun fmt --unsafe`
を実行してコミットしてみてください

2024-10-03 07:07 UTC, Astalum commented
done

2024-10-03 09:14 UTC, toririm requested changes
次回からレビューできる状態になったらレビュワーに私を設定するようにしてください

2024-10-03 09:14 UTC, toririm commented on package.json
> +    "@radix-ui/react-radio-group": "^1.2.0",
バージョンを落とす必要はないので、mainと同様のバージョンに戻してください。
また、`bun install` を実行して bun.lockb にも反映させてください。
```suggestion
    "@radix-ui/react-radio-group": "^1.2.1",
```

2024-10-04 04:30 UTC, toririm approved these changes
LGTM

2024-10-04 04:31 UTC, merged