Issue-256
toririm/cafeore-2024 pull request #259
Opened 2024-10-07 22:03 UTC by takum1-me

close #256

orderbyプロパティを削除し、statusプロパティを作成

serve画面にstatus遷移のボタンを追加

firebaseのバリテーションチェックの修正を行なった

2024-10-07 22:34 UTC, takum1-me reviewed
LGTM

2024-10-07 22:35 UTC, takum1-me commented
わかんなくなった！

2024-10-08 05:02 UTC, toririm requested changes
スキーマ変更なしなら _header.serve.tsx の変更だけで済むはず…？

2024-10-08 05:02 UTC, toririm commented on common/models/order.ts
> -  orderReady: z.boolean(),
servedAt が null or Date <=> 未提供 or 提供済み
orderReady が false or true <=> 準備中 or 準備完了

を使えば別にスキーマを変更する必要はない気がします

2024-10-08 05:02 UTC, toririm commented on pos/app/routes/_header.serve.tsx
> +      }
ここは別に callback に切り分けたさあり

2024-10-08 14:34 UTC, takum1-me commented on common/firebase-utils/converter.ts
ただしそう、単純に1つのstatusにまとめたかっただけなので、他に手を加えないで済む案を採用します

2024-10-08 16:22 UTC, toririm commented
ちなみにbiomeのvscode拡張入れたら保存時に自動でフォーマットしてくれるようになるから便利だよ

2024-10-08 16:31 UTC, takum1-me commented
ぐちゃぐちゃなので経緯をコピペし、一旦このPRはcloseにしたい

2024-10-08 16:31 UTC, closed without merging