受領後の画面作成
toririm/cafeore-2024 pull request #33
Opened 2024-08-28 21:52 UTC by Astalum

- 合計金額は mockOrder の total から取得
- 受領額の入力規制はかけていない
- 次へ進むで確認画面を表示
- 確認画面では合計金額・受領額・お釣りを表示

2024-08-29 14:12 UTC, toririm requested changes
ダイアログを使った確認画面のアイデアいいね！！

ただ、ここで依存してる`@radix-ui/react-alert-dialog`がpackage.jsonとbun.lockbに含まれてないからビルドが落ちてるかも

```sh
bun add @radix-ui/react-alert-dialog
```
を実行して発生するpackage.jsonとbun.lockbの差分をコミットしよう！

2024-08-29 14:22 UTC, toririm commented
ちなみに、shadcn/uiではコンポーネントを追加した際に、自動で依存パッケージのインストールが行われます！
package.jsonが変更されていたら、bun.lockbと合わせてコミットに含めるよう、気を付けてみるといいかも

2024-08-30 05:15 UTC, Astalum commented
不足分コミットしました～

2024-08-30 05:39 UTC, toririm approved these changes
@Astalum 

マージお願いします！

[![LGTMeow](https://lgtm-images.lgtmeow.com/2022/09/14/12/e4372f80-b057-4ad3-9be0-ad92e3694992.webp)](https://lgtmeow.com)

2024-08-30 05:39 UTC, toririm commented on app/routes/casher.tsx
実は

```diff
+ cashier
- casher
```

らしい

2024-08-30 05:47 UTC, merged