提供画面の作成（見た目だけ）
toririm/cafeore-2024 pull request #37
Opened 2024-08-30 19:52 UTC by Yayoi2078

ref #5 
とりあえず大まかなレイアウトから作りました。
メインの機能実装は起きたらやります。

2024-09-02 13:55 UTC, toririm requested changes
レビューの結果、しょうがはなにも悪くないことが判明……

2024-09-02 13:55 UTC, toririm commented on app/routes/_header.server.tsx
マジでしょうがは悪くないんだけど

Remixっていうフレームワークでは
`*.server.{js,ts,jsx,tsx}`
って命名のファイルをサーバーサイドでのみ実行するファイルだと認識するルールがあって……

提供の名称を変える必要がありそう…

2024-09-02 13:55 UTC, toririm commented on package.json
> +    "shadcn-ui": "^0.9.0",
これ、要らないので、removeしてbun.lockbも更新してください。
あるいはrevertできたらそれでもOK

2024-09-02 13:58 UTC, Yayoi2078 commented on app/routes/_header.server.tsx
な、なるほど…
一旦名称変えます

2024-09-02 13:58 UTC, Yayoi2078 commented on package.json
> +    "shadcn-ui": "^0.9.0",
了解です！

2024-09-03 04:21 UTC, toririm approved these changes
OKです
修正ありがとう！

2024-09-03 10:27 UTC, merged