issue/9
toririm/cafeore-2024 pull request #90
Opened 2024-09-11 11:29 UTC by takum1-me

issue #9

うまく実行できなかったら教えて欲しい

見た目を変えただけです

close #9

2024-09-11 13:21 UTC, toririm requested changes
TypeScriptのErrorはコメントの通りに修正すると取れます
```
bun lint --fix
bun fmt
```
を実行してESLintとPrettierのCIが通る状態にしてください

2024-09-11 13:21 UTC, toririm commented on app/routes/items/route.tsx
> +import React from 'react';
```suggestion
import { useMemo } from 'react';
```

2024-09-11 13:21 UTC, toririm commented on app/routes/items/route.tsx
> +  }, [items]);
```suggestion
  const sortedItems = useMemo<Record<ItemType, ItemEntity[]>>(() => {
    const base = { hot: [], ice: [], ore: [], milk: [] };
    if (!items) return base;
    return items.reduce<Record<ItemType, ItemEntity[]>>((acc, item) => {
      acc[item.type].push(item);
      return acc;
    }, base);
  }, [items]);
```

2024-09-11 17:57 UTC, takum1-me commented
よしいった！！！！

2024-09-12 01:04 UTC, toririm approved these changes
LGTM

2024-09-12 01:05 UTC, toririm commented
@takum1-me 
マージお願いします！

2024-09-12 09:19 UTC, merged