issue/40 提供画面の作成、各カップのstatus表示など
toririm/cafeore-2024 pull request #92
Opened 2024-09-11 19:01 UTC by takum1-me

一旦修正した、カードを作成して、各カップをタップするとstatusが変わる（色が変わる）ようにした

以下問題点
- 提供ボタンが押せない
- 同じ名前が2つ以上ある時（ex. 珈琲・俺ブレンドを２杯注文）、片方をクリックするともう片方のstatusも変わっちゃう

close #40
close #94

2024-09-11 19:01 UTC, takum1-me commented
一旦draftを作成

2024-09-12 03:34 UTC, toririm requested changes
ひとつのPRでいろいろやりすぎている印象があるので、PRの分割を検討してください
あるいはissueを切って、複数のissueをcloseするようにしてください
少なくとも #40 の領分は超えている気がします

2024-09-12 03:34 UTC, toririm commented on app/routes/_header.serve.tsx
> +}
`~/model/order.ts`のtypeを使ってください

2024-09-12 03:34 UTC, toririm commented on app/routes/_header.serve.tsx
> +  };
ロジックはactionに分離したいです
また、データのミューテーションはRepositoryを使用して行ってください

2024-09-12 13:33 UTC, takum1-me commented
issue #94 を作成

2024-09-12 13:34 UTC, takum1-me commented
Repositoryとかのところを理解せずにがちゃっとやったので、一旦そこら辺を確認します

2024-09-14 02:26 UTC, toririm commented on app/routes/_header.serve.tsx
> +}
定義したモデルに基づいてfirestoreのデータをパース＆バリデーションする仕組みが入っているので、モデルが一致しないデータを突っ込まれるとバグっちゃうんですよね……

servedAt は createdAt と同様に Date 型で定義してあるので、下の画像みたいに文字列が入っちゃうとエラーが発生しちゃうという話があります

![image](https://github.com/user-attachments/assets/f29df3c2-6a99-4ddf-bda2-76a815a07e63)

2024-09-27 04:28 UTC, closed without merging